#Macchine Learning Pipline
Read-->Split-->divide-->train-->predict-->evaluate

In [15]:
import numpy as np
import pandas as pd

data ={
    "area":[100,150,200,250,300,],
    "bedrooms":[2,3,3,4,5],
    "age":[20,15,10,5,2],
    "price":[200,300,400,500,650]
}

df=pd.DataFrame(data)
df.to_csv("housing.csv",index=False)

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score

#Step1 Read

In [17]:
df=pd.read_csv("housing.csv")
df.head()

   area  bedrooms  age  price
0   100         2   20    200
1   150         3   15    300
2   200         3   10    400
3   250         4    5    500
4   300         5    2    650

#Step2 Separate features and the label

In [18]:
x= df[["area","bedrooms","age"]]
y=df["price"]

#Step3 Splite the data

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

#Step 4Train modle
#step4.1 Create modle
#step4.2 Fit modle

In [20]:
model = LinearRegression()

In [21]:
model.fit(x_train,y_train)

LinearRegression()

#Step 5 Predict

In [22]:
y_pred=model.predict(x_test)

#Step 6 Evaluate

In [23]:
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
print("RMSE",rmse)
print("MSE",mse)
r2=r2_score(y_test,y_pred)
print("R2",r2)

RMSE 2.2737367544323206e-13
MSE 5.169878828456423e-26
R2 nan

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

#ML Pipline for linear classification

In [27]:
import numpy as np
import pandas as pd

data ={
    "hours_studied":[2,3,5,6,7,8,9,10], # Added '10' to make its length 8
    "attendance":[50,60,70,80,85,90,95,100],
    "passed":[0,0,0,1,1,1,1,1]
}

df=pd.DataFrame(data)
df.to_csv("Student_csv",index=False)

In [28]:
df=pd.read_csv("Student_csv")
df.head()

   hours_studied  attendance  passed
0              2          50       0
1              3          60       0
2              5          70       0
3              6          80       1
4              7          85       1

In [29]:
x= df[["hours_studied","attendance",]]
y=df["passed"]

In [30]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [34]:
from numpy.random import logistic
model = logistic()

In [44]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

In [46]:
model.fit(x_train,y_train)

LogisticRegression()

In [47]:
y_pred=model.predict(x_test)

In [48]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1_score = f1_score(y_test, y_pred)
print ("Accuracy:", accuracy)
print("Precision:", precision)
print ("Recall:", recall)
print ("F1 Score:", f1_score)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0